import { StyleSheet, Platform, Dimensions } from "react-native";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

/** Auth screen, settings, misc */
export const authStyles = StyleSheet.create({
  switchSubCompact: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  stepperSubRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 12,
    paddingTop: 4,
  },
  stepperSubRowTextCompact: {
    color: "#6e727a",
    fontSize: 12,
  },
  switchRowSeparator: {
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  modalStickyFooter: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    paddingTop: 16,
    marginTop: 8,
  },
  settingsBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderRadius: 18,
    height: 64,
    paddingHorizontal: 20,
    shadowColor: "#ffffff",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  settingsBoxLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  settingsBoxText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "500",
    marginLeft: 16,
    letterSpacing: 0.3,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  signOutCompactBtn: {
    borderColor: "rgba(255, 255, 255, 0.15)",
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 24,
  },
  signOutCompactBtnText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
  lightRootContainer: {
    backgroundColor: "#f4f4f8",
  },
  lightText: {
    color: "#0d0f14",
  },
  lightTextSub: {
    color: "#6e727a",
  },
  lightCard: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.07)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  lightTabBar: {
    backgroundColor: "#ffffff",
    borderTopColor: "rgba(0, 0, 0, 0.02)",
  },
  lightModal: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.08)",
  },
  lightInput: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.1)",
  },
  lightCodeBlock: {
    backgroundColor: "rgba(0, 0, 0, 0.03)",
    borderColor: "rgba(0, 0, 0, 0.06)",
  },
  lightCodeLine: {
    color: "#374151",
  },
  lightBorder: {
    borderColor: "rgba(0, 0, 0, 0.06)",
  },
  lightBorderTop: {
    borderTopColor: "rgba(0, 0, 0, 0.06)",
  },
  lightProgressBg: {
    backgroundColor: "rgba(0, 0, 0, 0.06)",
  },
  lightSessionContainer: {
    backgroundColor: "#f5f6f8",
  },

  // ────────────────────────────────────────────
  //  Press animation
  // ────────────────────────────────────────────
  pressedScale: {
    transform: [{ scale: 0.96 }],
    opacity: 0.88,
  },

  // ────────────────────────────────────────────
  //  Tab bar active dot indicator
  // ────────────────────────────────────────────
  tabActiveDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#00e5a0",
    marginTop: 4,
  },

  // ────────────────────────────────────────────
  //  Landing Screen
  // ────────────────────────────────────────────
  landingSafeArea: {
    flex: 1,
    backgroundColor: "#0B0F1C",
  },
  landingContainer: {
    flex: 1,
    backgroundColor: "#0B0F1C",
    paddingHorizontal: 28,
    justifyContent: "space-between",
    paddingTop: 20,
    paddingBottom: 36,
  },
  landingBlob1: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: "rgba(0, 229, 160, 0.07)",
    top: -60,
    right: -80,
  },
  landingBlob2: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(59, 130, 246, 0.06)",
    bottom: 80,
    left: -60,
  },
  landingBlob3: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(168, 85, 247, 0.05)",
    top: SCREEN_HEIGHT * 0.42,
    right: -30,
  },
  landingTopSection: {
    alignItems: "center",
    paddingTop: 40,
  },
  landingLogoRing: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(0, 229, 160, 0.35)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 229, 160, 0.06)",
    marginBottom: 24,
    shadowColor: "#00e5a0",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 8,
  },
  landingLogoInner: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#00e5a0",
    alignItems: "center",
    justifyContent: "center",
  },
  landingAppName: {
    fontSize: 38,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: -0.5,
    marginBottom: 10,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  landingTagline: {
    fontSize: 16,
    color: "#888888",
    textAlign: "center",
    lineHeight: 24,
    fontFamily: Platform.OS === "web" ? "Outfit, Inter, sans-serif" : undefined,
  },
  landingFeatures: {
    gap: 16,
    paddingVertical: 8,
  },
  landingFeatureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
  },
  landingFeatureIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  landingFeatureText: {
    flex: 1,
  },
  landingFeatureTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 3,
    fontFamily: Platform.OS === "web" ? "Outfit, Inter, sans-serif" : undefined,
  },
  landingFeatureSub: {
    color: "#666666",
    fontSize: 12,
    lineHeight: 17,
    fontFamily: Platform.OS === "web" ? "Outfit, Inter, sans-serif" : undefined,
  },
  landingCtaSection: {
    alignItems: "center",
    gap: 12,
  },
  landingCtaBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#00e5a0",
    height: 58,
    borderRadius: 16,
    width: "100%",
    shadowColor: "#00e5a0",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  landingCtaBtnText: {
    color: "#000000",
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.3,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  landingCtaNote: {
    color: "#555555",
    fontSize: 12,
    letterSpacing: 0.3,
    fontFamily: Platform.OS === "web" ? "Outfit, Inter, sans-serif" : undefined,
  },

  // ─── Animated splash centre layout ─────────────────────────────────────
  landingSplashCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  landingDotRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  landingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },


  // ─── Auth Screen ─────────────────────────────────────────────────
  authRoot: {
    flex: 1,
    minHeight: 600,
    backgroundColor: "#0B0F1C",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingBottom: 28,
    paddingTop: 8,
  },
  authBlobTL: {
    display: "none",
  },
  authBlobBR: {
    display: "none",
  },
  authHeroWrap: {
    width: 168,
    height: 168,
    borderRadius: 84,
    overflow: "hidden",
    marginTop: 20,
    marginBottom: 20,
    shadowColor: "#f59e0b",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 18,
    elevation: 10,
  },
  authHeroImg: {
    width: "100%",
    height: "100%",
  },
  authCopyBlock: {
    alignItems: "center",
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  authBigTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#ffffff",
    textAlign: "center",
    letterSpacing: -0.3,
    lineHeight: 30,
    marginBottom: 8,
  },
  authBigSub: {
    fontSize: 13,
    color: "#8888aa",
    textAlign: "center",
    lineHeight: 19,
  },
  authBtnStack: {
    width: "100%",
    gap: 10,
    marginBottom: 14,
  },
  authGooglePill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    backgroundColor: "#ffffff",
    borderRadius: 50,
    height: 48,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  authGooglePillText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111111",
  },
  authEmailPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 50,
    height: 48,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  authEmailPillText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#bbbbdd",
  },
  authLoginRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 2,
  },
  authLoginRowTxt: {
    fontSize: 13,
    color: "#8888aa",
  },
  authLoginLink: {
    fontSize: 13,
    fontWeight: "700",
    color: "#6366f1",
  },
  authSkipRow: {
    paddingVertical: 8,
    alignItems: "center",
  },
  authSkipTxt: {
    fontSize: 12,
    color: "#44445a",
    letterSpacing: 0.2,
  },
  // Email form sub-screen
  authBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    marginTop: 6,
    marginBottom: 2,
    paddingVertical: 4,
  },
  authBackText: {
    fontSize: 13,
    color: "#aaaacc",
    fontWeight: "500",
  },
  authEmailBody: {
    flex: 1,
    width: "100%",
    paddingTop: 8,
  },
  authPillToggle: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 50,
    padding: 3,
    marginBottom: 16,
    marginTop: 14,
  },
  authPillBtn: {
    flex: 1,
    height: 34,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  authPillBtnOn: {
    backgroundColor: "#6366f1",
  },
  authPillText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#55557a",
  },
  authPillTextOn: {
    color: "#ffffff",
  },
  authField: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    height: 48,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  authFieldInput: {
    flex: 1,
    fontSize: 14,
    color: "#ffffff",
  },
  authErrBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "rgba(239,68,68,0.08)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.18)",
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 10,
  },
  authErrTxt: {
    fontSize: 12,
    color: "#f87171",
    flex: 1,
    lineHeight: 17,
  },
  authBigGreenBtn: {
    backgroundColor: "#6366f1",
    borderRadius: 50,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
    marginTop: 4,
    marginBottom: 12,
  },
  authBigGreenBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 0.2,
}});
