import { StyleSheet } from "react-native";

/** Layout, home, quiz card, quiz options */
export const layoutStyles = StyleSheet.create({
export const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: "#0B0F1E",
    overflow: "hidden",
  },
  screenContainer: {
    flex: 1,
    overflow: "hidden",
  },
  homeContainer: {
    flex: 1,
    backgroundColor: "#0B0F1E",
  },
  topHeaderBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 12,
    height: 60,
    marginBottom: 16,
  },
  homeLogoText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "bold",
    letterSpacing: -0.5,
  },
  topHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  chatIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  avatarButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    overflow: "hidden",
  },
  headerAvatar: {
    width: "100%",
    height: "100%",
  },
  homeScroll: {
    flex: 1,
  },
  homeScrollContent: {
    paddingBottom: 24,
  },
  homeGreeting: {
    fontSize: 14,
    color: "#6e727a",
  },
  homeSectionTitle: {
    fontSize: 22,
    fontWeight: "500",
    color: "#ffffff",
    marginTop: 6,
    marginBottom: 18,
    letterSpacing: 0.6,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  quizCardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  playBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#00e5a0",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyWelcomeContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 50,
    paddingHorizontal: 16,
  },
  emptyIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 8,
  },
  emptyDesc: {
    fontSize: 14,
    color: "#888888",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 8,
  },
  emptyActionHint: {
    marginTop: 32,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    padding: 20,
    borderRadius: 20,
    width: "100%",
  },
  emptyActionText: {
    fontSize: 14,
    color: "#cccccc",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 12,
  },
  arrowDownAnimation: {
    marginTop: 4,
  },
  quizOptionsCard: {
    backgroundColor: "#0d0f14",
    borderRadius: 24,
    padding: 20,
    width: SCREEN_WIDTH - 32,
    maxHeight: "85%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    alignSelf: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 8,
  },
  optionsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    paddingBottom: 16,
    marginBottom: 16,
  },
  optionsTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
  },
  optionsSubtitle: {
    color: "#6e727a",
    fontSize: 13,
    marginTop: 2,
  },
  optionsCloseButton: {
    padding: 4,
  },
  optionsScroll: {
    flexShrink: 1,
  },
  optionsScrollContent: {
    paddingBottom: 16,
  },
  optionsSectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#6e727a",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 16,
    marginBottom: 12,
  },
  sectionCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 8,
  },
  optionRowContainer: {
    marginBottom: 12,
  },
  radioOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  radioCircleActive: {
    borderColor: "#00e5a0",
    backgroundColor: "#00e5a0",
  },
  radioCircleDisabled: {
    borderColor: "rgba(255, 255, 255, 0.05)",
    opacity: 0.4,
  },
  radioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#0d0f14",
  },
  radioLabel: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
  radioTextDisabled: {
    color: "rgba(255, 255, 255, 0.2)",
  },
  radioSub: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  inlineControlsContainer: {
    marginTop: 8,
    paddingLeft: 32,
  },
  rangeStepperGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rangeToText: {
    color: "#6e727a",
    fontSize: 12,
  },
  stepperContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderRadius: 8,
    height: 36,
  },
  stepperBtn: {
    width: 36,
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  stepperBtnDisabled: {
    opacity: 0.3,
  },
  stepperValueContainer: {
    width: 48,
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255, 255, 255, 0.06)",
    borderRightWidth: 1,
    borderRightColor: "rgba(255, 255, 255, 0.06)",
    height: "100%",
  },
  stepperValueText: {
    color: "#00e5a0",
    fontWeight: "bold",
    fontSize: 13,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
  },
  switchRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    marginRight: 12,
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  switchLabel: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
  switchSub: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  stepperSubRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.04)",
  },
  stepperSubRowText: {
    color: "#6e727a",
    fontSize: 13,
  },
  summaryCard: {
    backgroundColor: "rgba(0, 229, 160, 0.04)",
    borderColor: "rgba(0, 229, 160, 0.15)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  summaryTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  summaryQuestionCount: {
    color: "#00e5a0",
    fontSize: 22,
    fontWeight: "bold",
  },
  summaryText: {
    color: "#6e727a",
    fontSize: 12,
    marginBottom: 12,
  },
  warningBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    borderColor: "rgba(245, 158, 11, 0.2)",
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  warningText: {
    color: "#f59e0b",
    fontSize: 12,
  },
  startQuizBtn: {
    backgroundColor: "#6366f1",
    paddingVertical: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  startQuizBtnDisabled: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    shadowOpacity: 0,
    opacity: 0.4,
  },
  startQuizBtnText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 15,
  },
  quizActionsContainer: {
    gap: 8,
  },
  actionBtnRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    height: 44,
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  actionBtnRowText: {
    color: "#cccccc",
    fontSize: 14,
    fontWeight: "500",
  },
  tabLabel: {
    fontSize: 10,
    color: "#6e727a",
    marginTop: 2,
    fontWeight: "600",
    letterSpacing: -0.1,
  },
  tabLabelActive: {
    color: "#6366f1",
  },
  qCreateBtn: {
    // unused — Create button now uses plain tabItem style
  },
  bottomTabBar: {
    flexDirection: "row",
    backgroundColor: "#0B0F1E",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.02)",
    paddingTop: 10,
    alignItems: "center",
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    gap: 3,
  },
  centerTabContainer: {
    flex: 1.2,
    alignItems: "center",
    justifyContent: "center",
  },
  centerOuterRing: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#ffffff",
    padding: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  centerOuterActive: {
    borderColor: "#00e5a0",
  },
  centerRingPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.96 }],
  },
  centerInnerCircle: {
    backgroundColor: "#ffffff",
    width: "100%",
    height: "100%",
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
  },
}});
