import { StyleSheet, Platform, Dimensions } from "react-native";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");


export const styles = StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: "#0B0F1E",
    overflow: "hidden",
  },
  screenContainer: {
    flex: 1,
    overflow: "hidden",
  },
  homeContainer: {
    flex: 1,
    backgroundColor: "#0B0F1E",
  },
  topHeaderBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 12,
    height: 60,
    marginBottom: 16,
  },
  homeLogoText: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "bold",
    letterSpacing: -0.5,
  },
  topHeaderRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  chatIconButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  avatarButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    overflow: "hidden",
  },
  headerAvatar: {
    width: "100%",
    height: "100%",
  },
  homeScroll: {
    flex: 1,
  },
  homeScrollContent: {
    paddingBottom: 24,
  },
  homeGreeting: {
    fontSize: 14,
    color: "#6e727a",
  },
  homeSectionTitle: {
    fontSize: 22,
    fontWeight: "500",
    color: "#ffffff",
    marginTop: 6,
    marginBottom: 18,
    letterSpacing: 0.6,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  quizCardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  playBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#00e5a0",
    alignItems: "center",
    justifyContent: "center",
  },
  deleteBadge: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyWelcomeContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 50,
    paddingHorizontal: 16,
  },
  emptyIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 8,
  },
  emptyDesc: {
    fontSize: 14,
    color: "#888888",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 8,
  },
  emptyActionHint: {
    marginTop: 32,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    padding: 20,
    borderRadius: 20,
    width: "100%",
  },
  emptyActionText: {
    fontSize: 14,
    color: "#cccccc",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 12,
  },
  arrowDownAnimation: {
    marginTop: 4,
  },
  quizOptionsCard: {
    backgroundColor: "#0d0f14",
    borderRadius: 24,
    padding: 20,
    width: SCREEN_WIDTH - 32,
    maxHeight: "85%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    alignSelf: "center",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 8,
  },
  optionsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    paddingBottom: 16,
    marginBottom: 16,
  },
  optionsTitle: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
  },
  optionsSubtitle: {
    color: "#6e727a",
    fontSize: 13,
    marginTop: 2,
  },
  optionsCloseButton: {
    padding: 4,
  },
  optionsScroll: {
    flexShrink: 1,
  },
  optionsScrollContent: {
    paddingBottom: 16,
  },
  optionsSectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#6e727a",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: 16,
    marginBottom: 12,
  },
  sectionCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 8,
  },
  optionRowContainer: {
    marginBottom: 12,
  },
  radioOptionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  radioCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  radioCircleActive: {
    borderColor: "#00e5a0",
    backgroundColor: "#00e5a0",
  },
  radioCircleDisabled: {
    borderColor: "rgba(255, 255, 255, 0.05)",
    opacity: 0.4,
  },
  radioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#0d0f14",
  },
  radioLabel: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
  radioTextDisabled: {
    color: "rgba(255, 255, 255, 0.2)",
  },
  radioSub: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  inlineControlsContainer: {
    marginTop: 8,
    paddingLeft: 32,
  },
  rangeStepperGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rangeToText: {
    color: "#6e727a",
    fontSize: 12,
  },
  stepperContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderRadius: 8,
    height: 36,
  },
  stepperBtn: {
    width: 36,
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  stepperBtnDisabled: {
    opacity: 0.3,
  },
  stepperValueContainer: {
    width: 48,
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255, 255, 255, 0.06)",
    borderRightWidth: 1,
    borderRightColor: "rgba(255, 255, 255, 0.06)",
    height: "100%",
  },
  stepperValueText: {
    color: "#00e5a0",
    fontWeight: "bold",
    fontSize: 13,
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
  },
  switchRowLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    marginRight: 12,
  },
  iconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  switchLabel: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
  switchSub: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  stepperSubRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.04)",
  },
  stepperSubRowText: {
    color: "#6e727a",
    fontSize: 13,
  },
  summaryCard: {
    backgroundColor: "rgba(0, 229, 160, 0.04)",
    borderColor: "rgba(0, 229, 160, 0.15)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    marginBottom: 8,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  summaryTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  summaryQuestionCount: {
    color: "#00e5a0",
    fontSize: 22,
    fontWeight: "bold",
  },
  summaryText: {
    color: "#6e727a",
    fontSize: 12,
    marginBottom: 12,
  },
  warningBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(245, 158, 11, 0.08)",
    borderColor: "rgba(245, 158, 11, 0.2)",
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  warningText: {
    color: "#f59e0b",
    fontSize: 12,
  },
  startQuizBtn: {
    backgroundColor: "#6366f1",
    paddingVertical: 16,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  startQuizBtnDisabled: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    shadowOpacity: 0,
    opacity: 0.4,
  },
  startQuizBtnText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 15,
  },
  quizActionsContainer: {
    gap: 8,
  },
  actionBtnRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    height: 44,
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 4,
  },
  actionBtnRowText: {
    color: "#cccccc",
    fontSize: 14,
    fontWeight: "500",
  },
  tabLabel: {
    fontSize: 10,
    color: "#6e727a",
    marginTop: 2,
    fontWeight: "600",
    letterSpacing: -0.1,
  },
  tabLabelActive: {
    color: "#6366f1",
  },
  qCreateBtn: {
    // unused — Create button now uses plain tabItem style
  },
  bottomTabBar: {
    flexDirection: "row",
    backgroundColor: "#0B0F1E",
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.02)",
    paddingTop: 10,
    alignItems: "center",
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    gap: 3,
  },
  centerTabContainer: {
    flex: 1.2,
    alignItems: "center",
    justifyContent: "center",
  },
  centerOuterRing: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#ffffff",
    padding: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  centerOuterActive: {
    borderColor: "#00e5a0",
  },
  centerRingPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.96 }],
  },
  centerInnerCircle: {
    backgroundColor: "#ffffff",
    width: "100%",
    height: "100%",
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
  },
  opacityPress: {
    opacity: 0.7,
  },
  switchContainer: {
    width: 44,
    height: 26,
    borderRadius: 13,
    padding: 3,
    justifyContent: "center",
  },
  switchCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#ffffff",
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  tabHeader: {
    marginBottom: 24,
  },
  tabTitle: {
    fontSize: 32,
    fontWeight: "500",
    color: "#ffffff",
    letterSpacing: 0.8,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  tabSubtitle: {
    fontSize: 14,
    color: "#888888",
    marginTop: 6,
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "nowrap",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  panelCard: {
    paddingVertical: 20,
    paddingHorizontal: 20,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    marginBottom: 18,
  },
  statIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  statValue: {
    fontSize: 22,
    fontWeight: "600",
    color: "#ffffff",
    letterSpacing: 0.4,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  statLabel: {
    fontSize: 12,
    color: "#888888",
    marginTop: 4,
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  sectionHeading: {
    fontSize: 22,
    fontWeight: "500",
    color: "#ffffff",
    marginBottom: 18,
    marginTop: 12,
    letterSpacing: 0.6,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  quizCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderColor: "rgba(255, 255, 255, 0.09)",
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 18,
    marginBottom: 14,
    // Deep layered shadow for "card floating off the surface" feel
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 12,
  },
  attemptsBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  lightAttemptsBadge: {
    backgroundColor: "rgba(0, 0, 0, 0.03)",
    borderColor: "rgba(0, 0, 0, 0.06)",
  },
  attemptsBadgeText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#bbbbbb",
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  lightAttemptsBadgeText: {
    color: "#555555",
  },
  quizCardLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  quizAvatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 16,
  },
  quizAvatarText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 14,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  quizCardTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: 0.3,
    lineHeight: 22,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  quizCardMeta: {
    color: "#888888",
    fontSize: 12,
    marginTop: 4,
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  quizTime: {
    color: "#666666",
    fontSize: 12,
  },
  formContainer: {
    gap: 16,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ffffff",
    marginTop: 8,
  },
  webInputDummy: {
    backgroundColor: "#141930",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.07)",
    paddingHorizontal: 16,
    height: 48,
    justifyContent: "center",
  },
  formInput: {
    color: "#ffffff",
    fontSize: 15,
    width: "100%",
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryButton: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  categoryButtonActive: {
    backgroundColor: "#00e5a0",
    borderColor: "#00e5a0",
  },
  categoryButtonText: {
    color: "#cccccc",
    fontSize: 13,
    fontWeight: "500",
  },
  categoryButtonTextActive: {
    color: "#000000",
    fontWeight: "bold",
  },
  createButton: {
    backgroundColor: "#6366f1",
    height: 52,
    borderRadius: 26,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  createButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
  },
  videoPlayerCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 20,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  videoThumbnailPlaceholder: {
    height: 160,
    backgroundColor: "#16181e",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  youtubePlayCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#ff0000",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#ff0000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  videoDurationBadge: {
    position: "absolute",
    bottom: 8,
    right: 8,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "600",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  videoCardDetails: {
    padding: 12,
  },
  videoCardTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
  videoCardSub: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  guideStepCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  guideStepText: {
    color: "#cccccc",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  codeBlockContainer: {
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  codeLine: {
    color: "#b0b4bc",
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    fontSize: 12,
    lineHeight: 16,
  },
  codeTag: {
    color: "#ff79c6",
    fontWeight: "600",
  },
  codeAnswer: {
    color: "#00e5a0",
    fontWeight: "600",
  },
  codeComment: {
    color: "#6272a4",
    fontStyle: "italic",
  },
  codeWrong: {
    color: "#ff5555",
    fontWeight: "600",
  },
  guideStepTip: {
    color: "#888888",
    fontSize: 11,
    fontStyle: "italic",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  stepItemRow: {
    flexDirection: "row",
    gap: 12,
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
  },
  stepBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(0, 229, 160, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  stepBadgeText: {
    color: "#00e5a0",
    fontSize: 12,
    fontWeight: "bold",
  },
  stepItemTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  stepItemDesc: {
    color: "#6e727a",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
  profileSection: {
    alignItems: "center",
    marginBottom: 32,
  },
  profileDetailAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginBottom: 12,
  },
  profileDetailName: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "bold",
  },
  profileDetailEmail: {
    color: "#666666",
    fontSize: 13,
    marginTop: 2,
  },
  menuList: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 20,
    padding: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  menuItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuItemText: {
    color: "#dddddd",
    fontSize: 15,
    fontWeight: "500",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  centerModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#0d0f14",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 10,
    paddingHorizontal: 24,
    paddingBottom: 40,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderTopWidth: 1,
  },
  modalDragHandle: {
    width: 40,
    height: 5,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 24,
  },
  balanceDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  balanceDetailLabel: {
    color: "#999999",
    fontSize: 14,
  },
  balanceDetailValue: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
  },
  bankDetailContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderRadius: 16,
    padding: 16,
    marginTop: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  bankDetailLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  bankName: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
  bankMeta: {
    color: "#666666",
    fontSize: 11,
    marginTop: 2,
  },
  modalCloseButton: {
    backgroundColor: "#ffffff",
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 28,
  },
  modalCloseButtonText: {
    color: "#000000",
    fontSize: 15,
    fontWeight: "bold",
  },
  dialogCard: {
    backgroundColor: "#252836",
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 22,
    width: SCREEN_WIDTH - 32,
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.10)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.5,
    shadowRadius: 28,
    elevation: 16,
  },
  dialogIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  dialogTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 8,
  },
  dialogDescription: {
    fontSize: 14,
    color: "#bbbbbb",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 16,
  },
  dialogAmount: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 24,
  },
  dialogButtons: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  dialogCancel: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  dialogCancelText: {
    color: "#bbbbbb",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  dialogConfirm: {
    flex: 1,
    backgroundColor: "#00e5a0",
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    shadowColor: "#00e5a0",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  dialogConfirmText: {
    color: "#0d0f14",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  bottomSheetCard: {
    backgroundColor: "#0d0f14",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 8,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "ios" ? 36 : 20,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderTopWidth: 1,
    width: "100%",
  },
  bottomSheetTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 8,
    textAlign: "center",
  },
  bottomSheetOptionsContainer: {
    gap: 0,
    marginBottom: 12,
  },
  bottomSheetOptionBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomWidth: 0.5,
    borderBottomColor: "rgba(255, 255, 255, 0.07)",
    paddingVertical: 11,
    paddingHorizontal: 4,
    gap: 12,
  },
  bottomSheetIconBox: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheetOptionText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  bottomSheetOptionSub: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  bottomSheetCancelBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheetCancelBtnText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
  },
  sessionContainer: {
    flex: 1,
    backgroundColor: "#0B0F1E",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  sessionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    height: 60,
  },
  sessionCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  sessionQuizTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
    maxWidth: SCREEN_WIDTH - 160,
  },
  sessionProgressText: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  sessionTimerBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderColor: "rgba(0, 229, 160, 0.25)",
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  sessionTimerText: {
    color: "#00e5a0",
    fontWeight: "bold",
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    fontSize: 13,
  },
  progressBarBg: {
    height: 4,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    borderRadius: 2,
    overflow: "hidden",
    marginVertical: 8,
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#00e5a0",
    borderRadius: 2,
  },
  sessionScroll: {
    flex: 1,
    marginTop: 10,
  },
  sessionScrollContent: {
    paddingBottom: 40,
  },
  sessionQuestionCard: {
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  questionIndexRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  questionIndexCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#00e5a0",
    alignItems: "center",
    justifyContent: "center",
  },
  questionIndexCircleText: {
    color: "#000000",
    fontSize: 12,
    fontWeight: "bold",
  },
  questionTypeHelpText: {
    color: "#6e727a",
    fontSize: 11,
  },
  questionPromptText: {
    color: "#ffffff",
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "600",
  },
  sessionOptionsContainer: {
    gap: 8,
  },
  sessionOptionBtn: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 10,
  },
  sessionOptionBtnSelected: {
    backgroundColor: "rgba(0, 229, 160, 0.04)",
    borderColor: "rgba(0, 229, 160, 0.3)",
  },
  sessionOptionBtnCorrect: {
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderColor: "rgba(0, 229, 160, 0.5)",
  },
  sessionOptionBtnWrong: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderColor: "rgba(239, 68, 68, 0.4)",
  },
  optionLetterBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  optionLetterBoxSelected: {
    backgroundColor: "#00e5a0",
  },
  optionLetterBoxCorrect: {
    backgroundColor: "rgba(0, 229, 160, 0.2)",
  },
  optionLetterBoxWrong: {
    backgroundColor: "rgba(239, 68, 68, 0.2)",
  },
  optionLetterText: {
    color: "#888888",
    fontSize: 12,
    fontWeight: "bold",
  },
  optionContentText: {
    color: "#ffffff",
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
  sessionFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.05)",
  },
  sessionNavBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 6,
  },
  sessionNavBtnDisabled: {
    opacity: 0.3,
  },
  sessionNavBtnText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
  },
  finishSessionBtn: {
    backgroundColor: "#00e5a0",
    borderColor: "#00e5a0",
  },
  resultsScrollContent: {
    paddingBottom: 40,
    alignItems: "center",
  },
  resultsHeader: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
  },
  resultsIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  scoreSummaryCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 20,
    padding: 24,
    width: "100%",
    alignItems: "center",
    marginBottom: 20,
  },
  scoreTextBig: {
    color: "#00e5a0",
    fontSize: 48,
    fontWeight: "bold",
    letterSpacing: -1,
  },
  scoreSubText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    marginTop: 6,
  },
  xpBadge: {
    marginTop: 12,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderColor: "rgba(0, 229, 160, 0.2)",
    borderWidth: 1,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  xpBadgeText: {
    color: "#00e5a0",
    fontSize: 11,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 12,
    marginBottom: 24,
  },
  miniStatCard: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    alignItems: "center",
  },
  miniStatLabel: {
    color: "#6e727a",
    fontSize: 12,
    fontWeight: "500",
    marginBottom: 4,
  },
  miniStatValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
  },
  wrongQuestionItem: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    paddingVertical: 14,
  },
  wrongQuestionPrompt: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    marginBottom: 6,
  },
  wrongAnswerText: {
    color: "#ef4444",
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 2,
  },
  correctAnswerText: {
    color: "#00e5a0",
    fontSize: 12,
    lineHeight: 16,
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  chipBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 18,
  },
  chipBtnActive: {
    backgroundColor: "#8B5CF6",
    borderColor: "#8B5CF6",
  },
  chipBtnDisabled: {
    opacity: 0.3,
  },
  chipText: {
    color: "#cccccc",
    fontSize: 12,
    fontWeight: "500",
  },
  chipTextActive: {
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  chipTextDisabled: {
    color: "#555555",
  },
  compactControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  compactControlLabel: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "500",
  },
  sectionCardCompact: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginBottom: 16,
  },
  switchRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
  },
  switchLabelCompact: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
  switchSubCompact: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  stepperSubRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 12,
    paddingTop: 4,
  },
  stepperSubRowTextCompact: {
    color: "#6e727a",
    fontSize: 12,
  },
  switchRowSeparator: {
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  modalStickyFooter: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    paddingTop: 16,
    marginTop: 8,
  },
  settingsBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    borderColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderRadius: 18,
    height: 64,
    paddingHorizontal: 20,
    shadowColor: "#ffffff",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  settingsBoxLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  settingsBoxText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "500",
    marginLeft: 16,
    letterSpacing: 0.3,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  signOutCompactBtn: {
    borderColor: "rgba(255, 255, 255, 0.15)",
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 24,
  },
  signOutCompactBtnText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
  lightRootContainer: {
    backgroundColor: "#f4f4f8",
  },
  lightText: {
    color: "#0d0f14",
  },
  lightTextSub: {
    color: "#6e727a",
  },
  lightCard: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.07)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  lightTabBar: {
    backgroundColor: "#ffffff",
    borderTopColor: "rgba(0, 0, 0, 0.02)",
  },
  lightModal: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.08)",
  },
  lightInput: {
    backgroundColor: "#ffffff",
    borderColor: "rgba(0, 0, 0, 0.1)",
  },
  lightCodeBlock: {
    backgroundColor: "rgba(0, 0, 0, 0.03)",
    borderColor: "rgba(0, 0, 0, 0.06)",
  },
  lightCodeLine: {
    color: "#374151",
  },
  lightBorder: {
    borderColor: "rgba(0, 0, 0, 0.06)",
  },
  lightBorderTop: {
    borderTopColor: "rgba(0, 0, 0, 0.06)",
  },
  lightProgressBg: {
    backgroundColor: "rgba(0, 0, 0, 0.06)",
  },
  lightSessionContainer: {
    backgroundColor: "#f5f6f8",
  },

  // ────────────────────────────────────────────
  //  Press animation
  // ────────────────────────────────────────────
  pressedScale: {
    transform: [{ scale: 0.96 }],
    opacity: 0.88,
  },

  // ────────────────────────────────────────────
  //  Tab bar active dot indicator
  // ────────────────────────────────────────────
  tabActiveDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#00e5a0",
    marginTop: 4,
  },

  // ────────────────────────────────────────────
  //  Landing Screen
  // ────────────────────────────────────────────
  landingSafeArea: {
    flex: 1,
    backgroundColor: "#0B0F1C",
  },
  landingContainer: {
    flex: 1,
    backgroundColor: "#0B0F1C",
    paddingHorizontal: 28,
    justifyContent: "space-between",
    paddingTop: 20,
    paddingBottom: 36,
  },
  landingBlob1: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: "rgba(0, 229, 160, 0.07)",
    top: -60,
    right: -80,
  },
  landingBlob2: {
    position: "absolute",
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "rgba(59, 130, 246, 0.06)",
    bottom: 80,
    left: -60,
  },
  landingBlob3: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(168, 85, 247, 0.05)",
    top: SCREEN_HEIGHT * 0.42,
    right: -30,
  },
  landingTopSection: {
    alignItems: "center",
    paddingTop: 40,
  },
  landingLogoRing: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: "rgba(0, 229, 160, 0.35)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0, 229, 160, 0.06)",
    marginBottom: 24,
    shadowColor: "#00e5a0",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 8,
  },
  landingLogoInner: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: "#00e5a0",
    alignItems: "center",
    justifyContent: "center",
  },
  landingAppName: {
    fontSize: 38,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: -0.5,
    marginBottom: 10,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  landingTagline: {
    fontSize: 16,
    color: "#888888",
    textAlign: "center",
    lineHeight: 24,
    fontFamily: Platform.OS === "web" ? "Outfit, Inter, sans-serif" : undefined,
  },
  landingFeatures: {
    gap: 16,
    paddingVertical: 8,
  },
  landingFeatureRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
  },
  landingFeatureIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  landingFeatureText: {
    flex: 1,
  },
  landingFeatureTitle: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 3,
    fontFamily: Platform.OS === "web" ? "Outfit, Inter, sans-serif" : undefined,
  },
  landingFeatureSub: {
    color: "#666666",
    fontSize: 12,
    lineHeight: 17,
    fontFamily: Platform.OS === "web" ? "Outfit, Inter, sans-serif" : undefined,
  },
  landingCtaSection: {
    alignItems: "center",
    gap: 12,
  },
  landingCtaBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#00e5a0",
    height: 58,
    borderRadius: 16,
    width: "100%",
    shadowColor: "#00e5a0",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  landingCtaBtnText: {
    color: "#000000",
    fontSize: 17,
    fontWeight: "700",
    letterSpacing: 0.3,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  landingCtaNote: {
    color: "#555555",
    fontSize: 12,
    letterSpacing: 0.3,
    fontFamily: Platform.OS === "web" ? "Outfit, Inter, sans-serif" : undefined,
  },

  // ─── Animated splash centre layout ─────────────────────────────────────
  landingSplashCenter: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
  },
  landingDotRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 8,
  },
  landingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },


  // ─── Auth Screen ─────────────────────────────────────────────────
  authRoot: {
    flex: 1,
    minHeight: 600,
    backgroundColor: "#0B0F1C",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 28,
    paddingBottom: 28,
    paddingTop: 8,
  },
  authBlobTL: {
    display: "none",
  },
  authBlobBR: {
    display: "none",
  },
  authHeroWrap: {
    width: 168,
    height: 168,
    borderRadius: 84,
    overflow: "hidden",
    marginTop: 20,
    marginBottom: 20,
    shadowColor: "#f59e0b",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 18,
    elevation: 10,
  },
  authHeroImg: {
    width: "100%",
    height: "100%",
  },
  authCopyBlock: {
    alignItems: "center",
    marginBottom: 24,
    paddingHorizontal: 4,
  },
  authBigTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#ffffff",
    textAlign: "center",
    letterSpacing: -0.3,
    lineHeight: 30,
    marginBottom: 8,
  },
  authBigSub: {
    fontSize: 13,
    color: "#8888aa",
    textAlign: "center",
    lineHeight: 19,
  },
  authBtnStack: {
    width: "100%",
    gap: 10,
    marginBottom: 14,
  },
  authGooglePill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    backgroundColor: "#ffffff",
    borderRadius: 50,
    height: 48,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  authGooglePillText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111111",
  },
  authEmailPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 50,
    height: 48,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  authEmailPillText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#bbbbdd",
  },
  authLoginRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 2,
  },
  authLoginRowTxt: {
    fontSize: 13,
    color: "#8888aa",
  },
  authLoginLink: {
    fontSize: 13,
    fontWeight: "700",
    color: "#6366f1",
  },
  authSkipRow: {
    paddingVertical: 8,
    alignItems: "center",
  },
  authSkipTxt: {
    fontSize: 12,
    color: "#44445a",
    letterSpacing: 0.2,
  },
  // Email form sub-screen
  authBackBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    marginTop: 6,
    marginBottom: 2,
    paddingVertical: 4,
  },
  authBackText: {
    fontSize: 13,
    color: "#aaaacc",
    fontWeight: "500",
  },
  authEmailBody: {
    flex: 1,
    width: "100%",
    paddingTop: 8,
  },
  authPillToggle: {
    flexDirection: "row",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 50,
    padding: 3,
    marginBottom: 16,
    marginTop: 14,
  },
  authPillBtn: {
    flex: 1,
    height: 34,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  authPillBtnOn: {
    backgroundColor: "#6366f1",
  },
  authPillText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#55557a",
  },
  authPillTextOn: {
    color: "#ffffff",
  },
  authField: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    height: 48,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  authFieldInput: {
    flex: 1,
    fontSize: 14,
    color: "#ffffff",
  },
  authErrBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "rgba(239,68,68,0.08)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.18)",
    paddingHorizontal: 12,
    paddingVertical: 9,
    marginBottom: 10,
  },
  authErrTxt: {
    fontSize: 12,
    color: "#f87171",
    flex: 1,
    lineHeight: 17,
  },
  authBigGreenBtn: {
    backgroundColor: "#6366f1",
    borderRadius: 50,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#6366f1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
    marginTop: 4,
    marginBottom: 12,
  },
  authBigGreenBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 0.2,
  },
});
