import { StyleSheet } from "react-native";

/** Modals, inputs, buttons, badges */
export const uiStyles = StyleSheet.create({
  dialogIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  dialogTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 8,
  },
  dialogDescription: {
    fontSize: 14,
    color: "#bbbbbb",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 16,
  },
  dialogAmount: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 24,
  },
  dialogButtons: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  dialogCancel: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  dialogCancelText: {
    color: "#bbbbbb",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  dialogConfirm: {
    flex: 1,
    backgroundColor: "#00e5a0",
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    shadowColor: "#00e5a0",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  dialogConfirmText: {
    color: "#0d0f14",
    fontSize: 13,
    fontWeight: "600",
    letterSpacing: 0.2,
    fontFamily: Platform.OS === "web" ? "Outfit, Montserrat, Inter, sans-serif" : undefined,
  },
  bottomSheetCard: {
    backgroundColor: "#0d0f14",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 8,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "ios" ? 36 : 20,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderTopWidth: 1,
    width: "100%",
  },
  bottomSheetTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 8,
    textAlign: "center",
  },
  bottomSheetOptionsContainer: {
    gap: 0,
    marginBottom: 12,
  },
  bottomSheetOptionBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomWidth: 0.5,
    borderBottomColor: "rgba(255, 255, 255, 0.07)",
    paddingVertical: 11,
    paddingHorizontal: 4,
    gap: 12,
  },
  bottomSheetIconBox: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheetOptionText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  bottomSheetOptionSub: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  bottomSheetCancelBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  bottomSheetCancelBtnText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
  },
  sessionContainer: {
    flex: 1,
    backgroundColor: "#0B0F1E",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  sessionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    height: 60,
  },
  sessionCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.05)",
  },
  sessionQuizTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
    maxWidth: SCREEN_WIDTH - 160,
  },
  sessionProgressText: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  sessionTimerBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderColor: "rgba(0, 229, 160, 0.25)",
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  sessionTimerText: {
    color: "#00e5a0",
    fontWeight: "bold",
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    fontSize: 13,
  },
  progressBarBg: {
    height: 4,
    backgroundColor: "rgba(255, 255, 255, 0.07)",
    borderRadius: 2,
    overflow: "hidden",
    marginVertical: 8,
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: "#00e5a0",
    borderRadius: 2,
  },
  sessionScroll: {
    flex: 1,
    marginTop: 10,
  },
  sessionScrollContent: {
    paddingBottom: 40,
  },
  sessionQuestionCard: {
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  questionIndexRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
  },
  questionIndexCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "#00e5a0",
    alignItems: "center",
    justifyContent: "center",
  },
  questionIndexCircleText: {
    color: "#000000",
    fontSize: 12,
    fontWeight: "bold",
  },
  questionTypeHelpText: {
    color: "#6e727a",
    fontSize: 11,
  },
  questionPromptText: {
    color: "#ffffff",
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "600",
  },
  sessionOptionsContainer: {
    gap: 8,
  },
  sessionOptionBtn: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 10,
  },
  sessionOptionBtnSelected: {
    backgroundColor: "rgba(0, 229, 160, 0.04)",
    borderColor: "rgba(0, 229, 160, 0.3)",
  },
  sessionOptionBtnCorrect: {
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderColor: "rgba(0, 229, 160, 0.5)",
  },
  sessionOptionBtnWrong: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderColor: "rgba(239, 68, 68, 0.4)",
  },
  optionLetterBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  optionLetterBoxSelected: {
    backgroundColor: "#00e5a0",
  },
  optionLetterBoxCorrect: {
    backgroundColor: "rgba(0, 229, 160, 0.2)",
  },
  optionLetterBoxWrong: {
    backgroundColor: "rgba(239, 68, 68, 0.2)",
  },
  optionLetterText: {
    color: "#888888",
    fontSize: 12,
    fontWeight: "bold",
  },
  optionContentText: {
    color: "#ffffff",
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
  sessionFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.05)",
  },
  sessionNavBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 6,
  },
  sessionNavBtnDisabled: {
    opacity: 0.3,
  },
  sessionNavBtnText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
  },
  finishSessionBtn: {
    backgroundColor: "#00e5a0",
    borderColor: "#00e5a0",
  },
  resultsScrollContent: {
    paddingBottom: 40,
    alignItems: "center",
  },
  resultsHeader: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
  },
  resultsIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  scoreSummaryCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 20,
    padding: 24,
    width: "100%",
    alignItems: "center",
    marginBottom: 20,
  },
  scoreTextBig: {
    color: "#00e5a0",
    fontSize: 48,
    fontWeight: "bold",
    letterSpacing: -1,
  },
  scoreSubText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    marginTop: 6,
  },
  xpBadge: {
    marginTop: 12,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderColor: "rgba(0, 229, 160, 0.2)",
    borderWidth: 1,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  xpBadgeText: {
    color: "#00e5a0",
    fontSize: 11,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 12,
    marginBottom: 24,
  },
  miniStatCard: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    alignItems: "center",
  },
  miniStatLabel: {
    color: "#6e727a",
    fontSize: 12,
    fontWeight: "500",
    marginBottom: 4,
  },
  miniStatValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
  },
  wrongQuestionItem: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    paddingVertical: 14,
  },
  wrongQuestionPrompt: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    marginBottom: 6,
  },
  wrongAnswerText: {
    color: "#ef4444",
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 2,
  },
  correctAnswerText: {
    color: "#00e5a0",
    fontSize: 12,
    lineHeight: 16,
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  chipBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 18,
  },
  chipBtnActive: {
    backgroundColor: "#8B5CF6",
    borderColor: "#8B5CF6",
  },
  chipBtnDisabled: {
    opacity: 0.3,
  },
  chipText: {
    color: "#cccccc",
    fontSize: 12,
    fontWeight: "500",
  },
  chipTextActive: {
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  chipTextDisabled: {
    color: "#555555",
  },
  compactControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  compactControlLabel: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "500",
  },
  sectionCardCompact: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginBottom: 16,
  },
  switchRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
  },
  switchLabelCompact: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
}});
