import { StyleSheet, Platform, Dimensions } from "react-native";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

/** Video, profile, modal and menu styles — second half of session styles */
export const mediaStyles = StyleSheet.create({
  videoDurationBadge: {
    position: "absolute",
    bottom: 8,
    right: 8,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "600",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  videoCardDetails: {
    padding: 12,
  },
  videoCardTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
  videoCardSub: {
    color: "#6e727a",
    fontSize: 11,
    marginTop: 2,
  },
  guideStepCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 5,
  },
  guideStepText: {
    color: "#cccccc",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  codeBlockContainer: {
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.04)",
  },
  codeLine: {
    color: "#b0b4bc",
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    fontSize: 12,
    lineHeight: 16,
  },
  codeTag: {
    color: "#ff79c6",
    fontWeight: "600",
  },
  codeAnswer: {
    color: "#00e5a0",
    fontWeight: "600",
  },
  codeComment: {
    color: "#6272a4",
    fontStyle: "italic",
  },
  codeWrong: {
    color: "#ff5555",
    fontWeight: "600",
  },
  guideStepTip: {
    color: "#888888",
    fontSize: 11,
    fontStyle: "italic",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  stepItemRow: {
    flexDirection: "row",
    gap: 12,
    paddingBottom: 16,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.04)",
  },
  stepBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderWidth: 1,
    borderColor: "rgba(0, 229, 160, 0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  stepBadgeText: {
    color: "#00e5a0",
    fontSize: 12,
    fontWeight: "bold",
  },
  stepItemTitle: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  stepItemDesc: {
    color: "#6e727a",
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
  profileSection: {
    alignItems: "center",
    marginBottom: 32,
  },
  profileDetailAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginBottom: 12,
  },
  profileDetailName: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "bold",
  },
  profileDetailEmail: {
    color: "#666666",
    fontSize: 13,
    marginTop: 2,
  },
  menuList: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 20,
    padding: 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  menuItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuItemText: {
    color: "#dddddd",
    fontSize: 15,
    fontWeight: "500",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "flex-end",
  },
  centerModalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#0d0f14",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 10,
    paddingHorizontal: 24,
    paddingBottom: 40,
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderTopWidth: 1,
  },
  modalDragHandle: {
    width: 40,
    height: 5,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ffffff",
    marginBottom: 24,
  },
  balanceDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
  },
  balanceDetailLabel: {
    color: "#999999",
    fontSize: 14,
  },
  balanceDetailValue: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
  },
  bankDetailContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderRadius: 16,
    padding: 16,
    marginTop: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  bankDetailLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  bankName: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "bold",
  },
  bankMeta: {
    color: "#666666",
    fontSize: 11,
    marginTop: 2,
  },
  modalCloseButton: {
    backgroundColor: "#ffffff",
    height: 48,
    borderRadius: 24,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 28,
  },
  modalCloseButtonText: {
    color: "#000000",
    fontSize: 15,
    fontWeight: "bold",
  },
  dialogCard: {
    backgroundColor: "#252836",
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 22,
    width: SCREEN_WIDTH - 32,
    alignSelf: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.10)",
    shadowColor: "#000000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.5,
    shadowRadius: 28,
    elevation: 16,
  },
});
