import { StyleSheet, Platform, Dimensions } from "react-native";
const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get("window");

/** Card containers, list items, quiz cards, and display styles */
export const cardStyles = StyleSheet.create({
  questionPromptText: {
    color: "#ffffff",
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "600",
  },
  sessionOptionsContainer: {
    gap: 8,
  },
  sessionOptionBtn: {
    flexDirection: "row",
    alignItems: "flex-start",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 14,
    padding: 10,
    gap: 10,
  },
  sessionOptionBtnSelected: {
    backgroundColor: "rgba(0, 229, 160, 0.04)",
    borderColor: "rgba(0, 229, 160, 0.3)",
  },
  sessionOptionBtnCorrect: {
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderColor: "rgba(0, 229, 160, 0.5)",
  },
  sessionOptionBtnWrong: {
    backgroundColor: "rgba(239, 68, 68, 0.1)",
    borderColor: "rgba(239, 68, 68, 0.4)",
  },
  optionLetterBox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    alignItems: "center",
    justifyContent: "center",
  },
  optionLetterBoxSelected: {
    backgroundColor: "#00e5a0",
  },
  optionLetterBoxCorrect: {
    backgroundColor: "rgba(0, 229, 160, 0.2)",
  },
  optionLetterBoxWrong: {
    backgroundColor: "rgba(239, 68, 68, 0.2)",
  },
  optionLetterText: {
    color: "#888888",
    fontSize: 12,
    fontWeight: "bold",
  },
  optionContentText: {
    color: "#ffffff",
    fontSize: 14,
    flex: 1,
    lineHeight: 20,
  },
  sessionFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.05)",
  },
  sessionNavBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 6,
  },
  sessionNavBtnDisabled: {
    opacity: 0.3,
  },
  sessionNavBtnText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
  },
  finishSessionBtn: {
    backgroundColor: "#00e5a0",
    borderColor: "#00e5a0",
  },
  resultsScrollContent: {
    paddingBottom: 40,
    alignItems: "center",
  },
  resultsHeader: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
  },
  resultsIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  scoreSummaryCard: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 20,
    padding: 24,
    width: "100%",
    alignItems: "center",
    marginBottom: 20,
  },
  scoreTextBig: {
    color: "#00e5a0",
    fontSize: 48,
    fontWeight: "bold",
    letterSpacing: -1,
  },
  scoreSubText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "600",
    marginTop: 6,
  },
  xpBadge: {
    marginTop: 12,
    backgroundColor: "rgba(0, 229, 160, 0.1)",
    borderColor: "rgba(0, 229, 160, 0.2)",
    borderWidth: 1,
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  xpBadgeText: {
    color: "#00e5a0",
    fontSize: 11,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    gap: 12,
    marginBottom: 24,
  },
  miniStatCard: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 14,
    alignItems: "center",
  },
  miniStatLabel: {
    color: "#6e727a",
    fontSize: 12,
    fontWeight: "500",
    marginBottom: 4,
  },
  miniStatValue: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
  },
  wrongQuestionItem: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.06)",
    paddingVertical: 14,
  },
  wrongQuestionPrompt: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
    lineHeight: 20,
    marginBottom: 6,
  },
  wrongAnswerText: {
    color: "#ef4444",
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 2,
  },
  correctAnswerText: {
    color: "#00e5a0",
    fontSize: 12,
    lineHeight: 16,
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  chipBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 18,
  },
  chipBtnActive: {
    backgroundColor: "#8B5CF6",
    borderColor: "#8B5CF6",
  },
  chipBtnDisabled: {
    opacity: 0.3,
  },
  chipText: {
    color: "#cccccc",
    fontSize: 12,
    fontWeight: "500",
  },
  chipTextActive: {
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  chipTextDisabled: {
    color: "#555555",
  },
  compactControlsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  compactControlLabel: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "500",
  },
  sectionCardCompact: {
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginBottom: 16,
  },
  switchRowCompact: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
  },
  switchLabelCompact: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "500",
  },
});
